### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by iKap** [ezrec/niledelta#1]
Printer type: Delta (custom design based on KosselPro)
Electronics: Mega2560+Ramps 1.4
Firmware: Repetier 092.9
When I run niledelta,
`python niledelta.py \\.\COM4 250000`
it probes the bed 13 points and draw the graphic
after that It seems try to solve something and put a mess to the console (some loop printout)
than print error 
**ValueError: math domain error**
and stops

```
Bed Height: 360.800mm
Steps per mm: 100.000
Bed Level A: 0.000mm (0.000 turns)
Bed Level B: 0.000mm (0.000 turns)
Bed Level C: 0.000mm (0.000 turns)
Endstop X: 0.000mm (0 steps)
Endstop Y: 2.020mm (202 steps)
Endstop Z: 0.540mm (54 steps)
Radius A: 300.400mm
Radius B: 300.400mm
Radius C: 300.400mm
Angle A: 210.000 deg
Angle B: 330.000 deg
Angle C: 90.000 deg
Diagonal Rod A: 300.600mm
Diagonal Rod B: 300.600mm
Diagonal Rod C: 300.600mm
[27669.206009755813, 29144.28691157129]
MinFactor: 0 0.100 (err = 27669.206)

Bed Height: 360.800mm
Steps per mm: 100.000
Bed Level A: 0.000mm (0.000 turns)
Bed Level B: 0.000mm (0.000 turns)
Bed Level C: 0.000mm (0.000 turns)
Endstop X: 0.000mm (0 steps)
Endstop Y: 2.020mm (202 steps)
Endstop Z: 0.540mm (54 steps)
Radius A: 300.500mm
Radius B: 300.500mm
Radius C: 300.500mm
Angle A: 210.000 deg
Angle B: 330.000 deg
Angle C: 90.000 deg
Diagonal Rod A: 300.600mm
Diagonal Rod B: 300.600mm
Diagonal Rod C: 300.600mm
Traceback (most recent call last):
  File "niledelta.py", line 35, in <module>
    if __name__ == "__main__": main(sys.argv[1], sys.argv[2])
  File "niledelta.py", line 32, in main
    delta.calibrate()
  File "D:\Dev\niledelta\McCalibrate.py", line 155, in calibrate
    sumOfSquares[i] += self._perturb(i, delta_points[p], motor_points[p], perturb)
  File "D:\Dev\niledelta\McCalibrate.py", line 95, in _perturb
    alt_pos = delta.motor_to_delta(motor)
  File "D:\Dev\niledelta\Delta.py", line 245, in motor_to_delta
    z = (minusHalfB - math.sqrt(math.pow(minusHalfB, 2) - A * C)) / A
ValueError: math domain error
```

**Comment by ezrec** [comment]
Looks like "A" is very tiny (or zero), causing this issue.

Unfortunately, although I had high aspirations for it, I never successfully converted dc42's math to python.

The rest of the code seems to work - the GCode interaction with repetier, the firmware eeprom updates, etc.

I just couldn't get the math right to resolve to reasonable values.

If you are able to fork & fix that aspect of the code, I would be more than happy to pull your changes!
